// Generated by CoffeeScript 1.10.0
(function() {
  var content_tables, freshJobsButton, get_jobs_elements, init_counters, is_in_find_work_page, is_in_proposals_page, is_in_saved_jobs_page, is_same_page, is_should_show_counters, load_counters_data_for, moreJobsButton, pseudo_callback, show_counters;

  is_same_page = function(url) {
    return location.pathname.indexOf(url) > -1;
  };

  is_in_find_work_page = function() {
    return is_same_page('find-work-home');
  };

  is_in_saved_jobs_page = function() {
    return is_same_page('jobs/saved');
  };

  is_in_proposals_page = function() {
    return is_same_page('applications/active');
  };

  is_should_show_counters = function() {
    return is_in_find_work_page() || is_in_saved_jobs_page();
  };

  get_jobs_elements = function() {
    var jobs, jobsWrapper;
    jobsWrapper = document.getElementsByTagName('section')[0];
    return jobs = jobsWrapper.getElementsByTagName('article');
  };

  show_counters = function(data, jobEl) {
    var applicants_count, counters, el, interviewing_count;
    applicants_count = data.applicants.length;
    interviewing_count = data.invitedToInterview;
    counters = jobEl.getElementsByClassName('counters');
    if (counters.length) {
      el = counters[0];
    } else {
      el = document.createElement('span');
      el.className = 'counters';
      jobEl.appendChild(el);
    }
    return el.innerText = "Applicants: " + applicants_count + " | Interviewing: " + interviewing_count;
  };

  load_counters_data_for = function(jobEl) {
    var url, xhr;
    url = jobEl.getAttribute('data-id');
    xhr = new XMLHttpRequest;
    xhr.open('GET', '/jobs/' + url + '/applicants');
    xhr.onreadystatechange = function() {
      var response;
      if (xhr.readyState !== 4) {
        return;
      }
      if (xhr.response && xhr.response.length) {
        response = JSON.parse(xhr.response);
        return show_counters(response, jobEl);
      }
    };
    return xhr.send();
  };

  init_counters = function() {
    var jobs;
    if (is_should_show_counters()) {
      jobs = get_jobs_elements();
      return Array.prototype.forEach.call(jobs, function(job) {
        return load_counters_data_for(job);
      });
    }
  };

  pseudo_callback = function() {};

  init_counters();

  setInterval(init_counters, 60 * 1000);

  if (is_in_find_work_page()) {
    moreJobsButton = document.getElementById('jsLoadMoreJobs');
    freshJobsButton = document.getElementById('');
    if (moreJobsButton != null) {
      moreJobsButton.addEventListener('click', pseudo_callback);
    }
    if (freshJobsButton != null) {
      freshJobsButton.addEventListener('click', pseudo_callback);
    }
  }

  if (is_in_proposals_page()) {
    content_tables = document.getElementsByTagName('table');
    Array.prototype.forEach.call(content_tables, function(content_table) {
      var content, header, links;
      header = content_table.getElementsByTagName('thead')[0];
      content = content_table.getElementsByTagName('tbody')[0];
      links = content.getElementsByTagName('a');
      return Array.prototype.forEach.call(links, function(link) {
        var url, xhr;
        url = link.getAttribute('href');
        xhr = new XMLHttpRequest;
        xhr.open('GET', url);
        xhr.onreadystatechange = function() {
          var target_phrase, target_segmant;
          if (xhr.response && xhr.response.length) {
            target_phrase = 'Activity for this job';
            target_segmant = xhr.response.substr(xhr.response.indexOf(target_phrase) + target_phrase.length, 250);
            target_segmant = target_segmant.split('li');
            target_segmant.shift();
            return console.log(target_segmant);
          }
        };
        return xhr.send();
      });
    });
  }

}).call(this);
