// Generated by CoffeeScript 1.10.0
(function() {
  var get_jobs_elements, is_should_show_counters, jobs, load_counters_data_for, show_counters;

  is_should_show_counters = function() {
    if (location.pathname.indexOf('find-work-home') > -1) {
      return true;
    }
    if (location.pathname.indexOf('/jobs/saved') > -1) {
      return true;
    }
    return false;
  };

  get_jobs_elements = function() {
    var jobs, jobsWrapper;
    jobsWrapper = document.getElementsByTagName('section')[0];
    return jobs = jobsWrapper.getElementsByTagName('article');
  };

  show_counters = function(data, jobEl) {
    var applicants_count, counters, el, interviewing_count;
    applicants_count = data.applicants.length;
    interviewing_count = data.invitedToInterview;
    counters = jobEl.getElementsByClassName('counters');
    if (counters.length) {
      el = counters[0];
    } else {
      el = document.createElement('span');
      el.className = 'counters';
      jobEl.appendChild(el);
    }
    return el.innerText = "Applicants: " + applicants_count + " | Interviewing: " + interviewing_count;
  };

  load_counters_data_for = function(jobEl) {
    var url, xhr;
    url = jobEl.getAttribute('data-id');
    xhr = new XMLHttpRequest;
    xhr.open('GET', '/jobs/' + url + '/applicants');
    xhr.onreadystatechange = function() {
      var response;
      if (xhr.readyState !== 4) {
        return;
      }
      if (xhr.response && xhr.response.length) {
        response = JSON.parse(xhr.response);
        return show_counters(response, jobEl);
      }
    };
    return xhr.send();
  };

  if (is_should_show_counters()) {
    jobs = get_jobs_elements();
    Array.prototype.forEach.call(jobs, function(job) {
      return load_counters_data_for(job);
    });
  }

}).call(this);
